title: CSCB20
description: >-
  Introduction to Databases and Web Applications
baseurl: /cscb20

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed

# Excludes
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
